// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Todos$ReactHooksTemplate = require("./Todos/Todos.bs.js");

function App(Props) {
  var title = Props.title;
  return React.createElement("div", {
              className: "app"
            }, React.createElement("div", {
                  className: "title"
                }, title), React.createElement(Todos$ReactHooksTemplate.make, { }));
}

var make = App;

exports.make = make;
/* react Not a pure module */
