// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var React = require("react");

function App(Props) {
  var title = Props.title;
  var match = React.useReducer((function (state, action) {
          return state;
        }), /* record */[/* items : :: */[
          /* record */[
            /* title */"Some todo item",
            /* completed */false
          ],
          /* [] */0
        ]]);
  var numItems = List.length(match[0][/* items */0]);
  return React.createElement("div", {
              className: "app"
            }, React.createElement("div", {
                  className: "title"
                }, title), React.createElement("div", {
                  className: "items"
                }, "Empty"), React.createElement("div", {
                  className: "footer"
                }, String(numItems) + " items "));
}

var make = App;

exports.make = make;
/* react Not a pure module */
